function [Aircraft] = CeRAS(Aircraft)
%
% [Aircraft] = CeRAS(Aircraft)
% translated from Aviary phase_info by Max Arnson, May 2025
%
% Parametric mission for a typical regional jet or narrowbody aircraft.
% Phases: Pre-Mission (mass optimization), Climb, Cruise at 33k, Mid-Cruise Climb, Cruise at 35k, Descent.
%

%% IMPORT THE PERFORMANCE PARAMETERS %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

AltTko = 0;
AltCrs33 = UnitConversionPkg.ConvLength(33000, "ft", "m");
AltCrs35 = UnitConversionPkg.ConvLength(35000, "ft", "m");

VelMach78 = 0.78; % unitless Mach for cruise phases

%% MISSION TARGETS %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Mission.Target.Valu = [UnitConversionPkg.ConvLength(2500*0.35, "naut mi", "m"); UnitConversionPkg.ConvLength(2500*0.65, "naut mi", "m")]; % Final cruise target range
Mission.Target.Type = ["Dist";"Dist"];

%% MISSION SEGMENTS %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Mission.Segs = [ ...
    "Climb"; "Cruise"; "Climb"; "Cruise"; "Descent" ...
];

Mission.ID = [1; 1; 2; 2; 2]; % Single mission, no separate reserve yet

Mission.AltBeg = [ ...
    AltTko; ...
    AltCrs33; ...
    AltCrs33; ...
    AltCrs35; ...
    AltCrs35 ...
];

Mission.AltEnd = [ ...
    AltCrs33; ...
    AltCrs33; ...
    AltCrs35; ...
    AltCrs35; ...
    AltTko ...
];

Mission.VelBeg = [ ...
    0.2;...
    VelMach78; ...
    VelMach78; ...
    VelMach78; ...
    0.78 ...
];

Mission.VelEnd = [ ...
    VelMach78;...
    VelMach78; ...
    VelMach78; ...
    VelMach78; ...
    0.2 ...
];

Mission.TypeBeg = [ ...
    "Mach"; ...
    "Mach"; ...
    "Mach"; ...
    "Mach"; ...
    "Mach" ...
];

Mission.TypeEnd = Mission.TypeBeg;

Mission.ClbRate = [ ...
    NaN; ... % Climb phase uses altitude targets, no explicit rate
    NaN; ...
    NaN; ...
    NaN; ...
    NaN ...
];

%% RESERVE / POST MISSION (Placeholder) %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% TODO: Add 45-min loiter at 10k ft + 100 nmi diversion (if required)

%% SAVE MISSION PROFILE %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Aircraft.Mission.Profile = Mission;

end